name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYENV_VERSION: "3.11.12"
      PYTHONPATH: src
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Run formatter check
        run: uv run --no-project ruff format --check .

      - name: Run linter
        run: uv run --no-project ruff check .

      - name: Run type checker
        run: uv run mypy .

      - name: Run tests
        run: uv run --no-project pytest -q
